### ISSUE TITLE
limit IE image size to 800

### ISSUE THREAD

**Issue by Fil** [nursit/AdaptiveImages#8]
the specific IE image tag should not necessarily be the largest image generated, but more probably one of the widths that is closest to 800px; for example, I generate images 4096px-wide as a maximum (for super-large screens), and IE receives 
`<!--[if IE]><img src='local/adapt-img/4096/10x/IMG/grande-roue.jpg?1391335966' width='3268' height='3292' class='adapt-img-ie c1092403088' /><![endif]-->`

which is probably too much for it :)

**Comment by Cerdic** [comment]
There's no more IE image in the html5 markup, so I'm closing this one
